### PR TITLE
Fix/event image upload error handling

### LINKED ISSUE #153: Event can be created with negative feedback to admin
:rotating_light: When creating event as admin, several separate HTTP requests to the backend is sent. As a result, the event may be added to the database even though the event creation page provides negative feekback "noe gikk galt" to the admin. This could result in creating duplicates.

:mag: In my case, a 401 was returned by the image endpoint when attempting to upload (due to an unrelated issue). This resulted in the following:
image

Despite this message, the event was successfully created (without image).

### PR DESCRIPTION
**Pull request by FredrikMorstad**
## :goal_net:  Better handling errors on image uploads
  - Resolves #153 
  - Gives users a new opportunity to reupload image if the upload failed
image
### :sparkles: FileSelector
  - component to handle all file selection on the website  
image
   - An validator can be provided, which is enforced by the component

### CODE REVIEW

File: src/components/molecules/event/eventBody/EventBody.tsx [hunk 1]
```diff
@@ -112,21 +110,47 @@ export const EditEvent: React.FC<{ event: Event; setEdit: () => void }> = ({
...
+      let detail = await error.getText();
+      if (error.statusCode === 400) {
+        addToast({
+          title: 'Ikke godkjent oppdatering',
+          status: 'error',
+          description: `${detail}`,
+        });
+        return;
+      }
+      addToast({
```
Comment (seblj) [inline src/components/molecules/event/eventBody/EventBody.tsx:139]: Do we need a return after this? Won't it show the success toast right after this if not?

File: src/components/molecules/event/eventBody/EventBody.tsx [hunk 2]
```diff
@@ -157,10 +181,12 @@ export const EditEvent: React.FC<{ event: Event; setEdit: () => void }> = ({
...
               style={{ boxSizing: 'border-box', width: '100%' }}
             />
-            <div className={styles.imgContainer}>
-              <label>Endre arrangement bilde </label>
-              <input type="file" accept="image/*" onChange={handleFileUpload} />
-            </div>
+            <FileSelector
+              setFile={setFile}
+              text="Endre arrangement bilde"
+              accept="image/png"
```
Comment (seblj) [inline src/components/molecules/event/eventBody/EventBody.tsx:187]: Should we only allow png? What about jpg, jpeg etc?

File: src/components/molecules/forms/eventForm/EventForm.tsx [hunk 3]
```diff
@@ -212,12 +238,21 @@ const EventForm = () => {
...
+        <FileSelector
+          setFile={setFile}
+          text="Last opp bilde til arrangementet"
+          fileValidator={PNGImageValidator}
+          accept="image/png"
+        />
       </form>
       <div>
+        <ReuploadImageModal
+          title="Last opp arrangementet bilde på nytt"
```
Comment (seblj) [inline src/components/molecules/forms/eventForm/EventForm.tsx:250]: Something other than "arrangementet bilde"

What about: "Last opp bilde til arrangementet på nytt"?

File: src/components/molecules/modals/reuploadModal/ReuploadModal.tsx [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+          />
+          <ConfirmationBox
+            confirmText="Last opp på nytt"
+            declineText="Ikke last opp nytt bilde"
+            onAccept={() => {
+              reuploadImage(id);
+            }}
+            onDecline={() => {
+              onClose();
+              redirAndDispalyFeedback();
```
Comment (seblj) [inline src/components/molecules/modals/reuploadModal/ReuploadModal.tsx:92]: Does it show success that the picture id added on decline?

File: src/components/molecules/modals/reuploadModal/ReuploadModal.tsx [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+        title: 'Feil ved opplasting av bilde',
+        status: 'error',
+        description: 'prøv på nytt',
+      });
+      return;
+    }
+    redirAndDispalyFeedback();
+  };
+
+  const redirAndDispalyFeedback = () => {
```
Comment (seblj) [inline src/components/molecules/modals/reuploadModal/ReuploadModal.tsx:51]: Display*

File: src/components/molecules/modals/reuploadModal/ReuploadModal.tsx [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+
+  useEffect(() => {
+    if (shouldOpen) {
+      onOpen();
+    }
+  }, [shouldOpen]);
+
+  useEffect(() => {
+    if (!isOpen && id !== undefined) {
+      // handles modal closed and users has not uploaded event
```
Comment (seblj) [inline src/components/molecules/modals/reuploadModal/ReuploadModal.tsx:68]: If this is for if user has not uploaded event, why do we call the function on the next line that displays success?

**Review by seblj — CHANGES_REQUESTED** [review]
Looks good for the most part I think, but some comments that should be resolved🙌

File: src/components/molecules/event/eventBody/EventBody.tsx (hunk 2 above)
Comment (FredrikMorstad) [reply src/components/molecules/event/eventBody/EventBody.tsx:187]: As of now, the API only support PNG so this can be removed when multiple files types are supported

File: src/components/molecules/modals/reuploadModal/ReuploadModal.tsx (hunk 6 above)
Comment (FredrikMorstad) [reply src/components/molecules/modals/reuploadModal/ReuploadModal.tsx:68]: Maybe bad wording, should be that `id !==undefined` guards against the component doing stuff before event is uploaded

File: src/api/event.ts [hunk 7]
```diff
@@ -11,8 +11,15 @@ import { get, post, put, Delete } from './requests';
 export const createEvent = (event: CreateEvent): Promise<{ eid: string }> =>
   post<{ eid: string }>('event/', event);
 
-export const uploadEventPicture = (id: string, eventImage: any) =>
-  post<{}>('event/' + id + '/image', eventImage, 'multipart/form-data');
+export const uploadEventPicture = async (id: string, imageFile: File) => {
+  const data = new FormData();
+  data.append('image', imageFile, imageFile.name);
+  try {
```
[the remark this answers is not in the document]
Comment (FredrikMorstad) [reply src/api/event.ts:17]: true, fixing now

File: src/components/molecules/event/eventBody/EventBody.tsx [hunk 8]
```diff
@@ -112,21 +110,47 @@ export const EditEvent: React.FC<{ event: Event; setEdit: () => void }> = ({
...
+      /* Check both file and payload as we the set error does not trigger if the 
+         file is set but the payload is not, and we cant send an empty payload*/
       if (Object.keys(updatePayload).length) {
         await updateEvent(event.eid, updatePayload);
       }
-      // reload page
-      history.go(0);
     } catch (error) {
-      console.log(error);
+      let detail = await error.getText();
```
[the remark this answers is not in the document]
Comment (FredrikMorstad) [reply src/components/molecules/event/eventBody/EventBody.tsx:130]: agree, should be `const`

File: src/components/molecules/event/eventBody/EventBody.tsx (hunk 1 above)
Comment (FredrikMorstad) [reply src/components/molecules/event/eventBody/EventBody.tsx:139]: yeah didn't see that :+1:

File: src/components/molecules/modals/reuploadModal/ReuploadModal.tsx (hunk 4 above)
Comment (FredrikMorstad) [reply src/components/molecules/modals/reuploadModal/ReuploadModal.tsx:92]: fixed now :+1:

File: src/components/molecules/event/eventBody/EventBody.tsx [hunk 9]
```diff
@@ -112,21 +110,48 @@ export const EditEvent: React.FC<{ event: Event; setEdit: () => void }> = ({
...
+    addToast({
+      title: 'Arrangement oppdatert',
+      status: 'success',
+    });
+
+    setTimeout(function () {
+      // reload page after 500 ms for better UX
+      // TODO: apply changes to component, avoiding data to be re fetched
+      history.go(0);
+    }, 300);
```
Comment (otytlandsvik) [inline src/components/molecules/event/eventBody/EventBody.tsx:154]: 500ms or 300ms?

File: src/components/molecules/forms/eventForm/EventForm.tsx [hunk 10]
```diff
@@ -79,28 +82,55 @@ const EventForm = () => {
...
+            title: 'En ukjent feil skjedde',
+            status: 'error',
+          });
           setError('Noe gikk galt');
           return;
       }
     }
   };
 
+  useEffect(() => {
```
Comment (seblj) [inline src/components/molecules/forms/eventForm/EventForm.tsx:130]: Remove🔥

**Review by seblj — APPROVED** [review]
Only one thing to remove🔥

**Review by otytlandsvik — APPROVED** [review]
LGTM, some comments and a console log can be removed.

File: src/components/molecules/forms/eventForm/EventForm.tsx (hunk 10 above)
Comment (FredrikMorstad) [reply src/components/molecules/forms/eventForm/EventForm.tsx:130]: that's an important feature!

File: src/components/molecules/modals/reuploadModal/ReuploadModal.tsx [hunk 11]
```diff
@@ -0,0 +1,107 @@
...
+        <div className="imgReupload">
+          <FileSelector
+            setFile={setFile}
+            text="En feil skjedde ved opplasting av bilde, prøv på nytt her."
+            accept="image/png"
+            fileValidator={PNGImageValidator}
+          />
+          <ConfirmationBox
+            confirmText="Last opp på nytt"
+            declineText="Ikke last opp nytt bilde"
```
[the remark this answers is not in the document]
Comment (FredrikMorstad) [reply src/components/molecules/modals/reuploadModal/ReuploadModal.tsx:91]: agree :+1:
